### ISSUE TITLE
인증, 보안 적용

### ISSUE THREAD

**Issue by ber01** [team-ksu-14/OutStagram#8]
- `Oauth2` 인증
- `Spring Security` 보안

**Comment by ber01** [comment]
하나의 `Member` 객체를 저장한 후 읽어오는 코드가 필요
- `Mono` 사용

**Comment by ber01** [comment]
~~~java
Mono.just(Member.builder()
        .id(UUID.randomUUID().toString())
        .email("email@email.com")
        .password("testPasswordPassword")
        .createdAt(LocalDateTime.now())
        .build()).flatMap(memberRepository::save).subscribe();
~~~

- `subscribe()`를 하지 않으면 저장이 되지 않는다. 왜?
-  `subscribe()` 이 전의 타입이 `Mono<Member>`가 되는 이유와 순서에 대해 공부가 필요

**Comment by woghd9072** [comment]
- `subscribe()`를 하지 않으면 저장이 되지 않는다. 왜?
    - 참조 : https://javacan.tistory.com/entry/Reactor-Start-1-RS-Flux-Mono-Subscriber
    - 시퀀스는 신호를 바로 발생하지 않는다. 구독을 하는 시점에 신호를 발생하게 시작한다.

**Comment by ber01** [comment]
`UserDetailsService` 를 상속하여 `MemberService`를 구현
- `null`에 대한 처리가 필요해 보인다.
    - ` Optional`을 사용해볼까?
- `password` 인코딩 추가 예정

**Comment by ber01** [comment]
~~~java
Mono<Member> memberMono = memberRepository.findByEmail(username);
Member member = memberMono.block();

if (member == null) {
    throw new UsernameNotFoundException(username);
}
~~~

- `null` 처리는 `exception`을 발생하도록 하였으나 추후에 수정이 필요할 것 같음

**Comment by woghd9072** [comment]
- MapReactiveUserDetailsService를 사용하면 UserDetailsService를 Mono 또는 Flux 형태로 받는거 같음
    - https://www.baeldung.com/spring-security-5-reactive
    - https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/userdetails/MapReactiveUserDetailsService.html
    - 관련 자료임

**Comment by woghd9072** [comment]
- `ReactiveUserDetails` & `WebFluxSecurity` 참고 자료
    - https://www.naturalprogrammer.com/blog/18149/reactive-spring-security-webflux-rest-web-services

**Comment by ber01** [comment]
- `MapReactiveUserDetailsService` 를 `UserDetailsService` 의 `loadUserByUsername` 처럼 해보려고 하였으나 오류 발생
- `UserDetailsService` 를 이용하면 테스트가 깨지지는 않으므로 일단은 진행

**Comment by ber01** [comment]
- `UserDetailsService` 를 `implements` 하여 `User` 객체를 반환하는 방법은 간단하지만 속도를 많이 저하시킨다고 함
- 우선은 기능 구현이 목적이므로 현 방법을 유지

**Comment by ber01** [comment]
- 인증 토큰을 발급 받기 위해 테스트 진행 중 `mockMvc` 를 `webTestClient` 로 작성하는데 어려움이 있어서 일단 `mockMvc` 로  진행 중
    - ~~`mockMvc`로 테스트를 진행하니 토큰이 발급되지 않음 의존성이 `web-flux`라서 그런 것이 아닐까 하는 생각이 드는데 확실하지는 않음~~
        - `subscribe` 를 안해서 제대로 저장이 이루어지지 않아 테스트가 안되었던 것...
    - ~~`webTestClient`로 변경을 어떻게 할지 감이 안잡혀서 `postman`으로 실험을 해보니 정상적으로 토큰을 받아오는 것을 확인~~
        - 얘도 테스트 코드 작성 완료

**Comment by ber01** [comment]
~~~java
mockMvc.perform(post("/oauth/token")
            .with(httpBasic(clientId, clientSecret))
            .param("username", email)
            .param("password", password)
            .param("grant_type", "password"))
        .andDo(print())
        .andExpect(status().isOk())
        .andExpect(jsonPath("access_token").exists())
;
~~~
- `mockMvc`를 이용하여 동작하던 코드를 `webTestClient`로 변경
~~~java
webTestClient
        .mutate().filter(basicAuthentication(clientId, clientSecret)).build()
        .post()
            .uri("/oauth/token")
            .body(BodyInserters.fromFormData(fromData))
        .exchange()
        .expectStatus().isOk()
        .expectBody().jsonPath("access_token").exists()
;
~~~
- 문법이 많이 달라서 찾는데 애를 많이 먹었다 .. 앞으로 참고하면서 하면 될 듯

**Comment by ber01** [comment]
- `GET` 요청은 인증 없이 그 외의 요청은 인증이 필요하게 테스트를 작성
    - `webTestClient`의 `response`의 토큰을 꺼내온 후 `header`에 추가하여 요청
        - ~~`response`를 꺼내오는 게 `mockMvc`와 달라서 또 찾는 중 ..~~
        - 찾았으나 보완이 꼭 필요함, 자세한 건 아래 댓글, `commit` 확인

**Comment by ber01** [comment]
- `mockMvc`로 토큰을 꺼내올 때 `ResultAction`의 `andReturn().getResponse().getContentAsString()`를 `webTestClient`로 변경 

~~~java
ResultActions perform = this.mockMvc.perform(post("/oauth/token")
        .with(httpBasic(clientId, clientSecret))
        .param("username", email)
        .param("password", password)
        .param("grant_type", "password"));

String contentAsString = perform.andReturn().getResponse().getContentAsString();
Jackson2JsonParser parser = new Jackson2JsonParser();
return parser.parseMap(contentAsString).get("access_token").toString();
~~~

~~~java
FluxExchangeResult<String> result = webTestClient.mutate().filter(basicAuthentication(clientId, clientSecret)).build()
        .post()
        .uri("/oauth/token")
        .body(BodyInserters.fromFormData(fromData))
        .exchange().returnResult(String.class);

String resultS = result.toString();
int start = resultS.indexOf("{");
int end = resultS.indexOf("}");

String content = resultS.substring(start, end + 1);

Jackson2JsonParser parser = new Jackson2JsonParser();

return parser.parseMap(content).get("access_token").toString();
~~~

- 아래와 같이 전체 결과를 가져올 수는 있는데 맨 밑의 토큰에 대한 정보만 들고오는 메서드는 따로 없는 것 같음
~~~java
> POST http://localhost:62438/oauth/token
> WebTestClient-Request-Id: [1]
> Authorization: [Basic bXlBcHA6cGFzcw==]
> Content-Type: [application/x-www-form-urlencoded;charset=UTF-8]
> Content-Length: [70]

username=authTest%40test.com&password=authPassword&grant_type=password

< 200 OK OK
< Cache-Control: [no-store]
< Pragma: [no-cache]
< X-Content-Type-Options: [nosniff]
< X-XSS-Protection: [1; mode=block]
< X-Frame-Options: [DENY]
< Content-Type: [application/json;charset=UTF-8]
< Transfer-Encoding: [chunked]
< Date: [Tue, 10 Dec 2019 10:54:36 GMT]

{"access_token":"d41680e0-8776-46bc-a0cf-323cb7067398","token_type":"bearer","refresh_token":"34ef162e-1b27-4ecc-9ae7-bdbac1627c05","expires_in":599,"scope":"read write"}
~~~
- `String` 타입으로 변경한 후에 필요한 부분만 뽑아내서 테스트가 성공은 했지만 상당히 `type-safe`하지 않음

**Comment by ber01** [comment]
현재 유저를 찾는 코드 까지 작성 완료
